import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import CookieBanner from '@/components/CookieBanner'

export const metadata: Metadata = {
  metadataBase: new URL('https://accountingskip.com'),
  title: {
    default: 'Accounting Skip — AI-Powered Bookkeeping for US Small Businesses',
    template: '%s | Accounting Skip',
  },
  description:
    'Accounting Skip is a Florida-based AI-powered bookkeeping firm. Our AI categorizes 80% of transactions instantly. QBO-certified team. Month-end close in 5 days. Starting at $349/month.',
  keywords: [
    'AI bookkeeping',
    'online bookkeeping service',
    'small business accounting',
    'QuickBooks bookkeeping',
    'e-commerce bookkeeping',
    'Amazon seller bookkeeping',
    'Shopify accounting',
    'virtual bookkeeper',
    'BPO bookkeeping',
    'Florida bookkeeping',
  ],
  authors: [{ name: 'Accounting Skip LLC' }],
  creator: 'Accounting Skip LLC',
  publisher: 'Accounting Skip LLC',
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://accountingskip.com',
    siteName: 'Accounting Skip',
    title: 'Accounting Skip — AI-Powered Bookkeeping for US Small Businesses',
    description:
      'Month-end close in 5 days. AI categorizes 80% of transactions. QBO-certified review. Starting at $349/month.',
    images: [
      {
        url: '/opengraph-image',
        width: 1200,
        height: 630,
        alt: 'Accounting Skip — AI-Powered Bookkeeping',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Accounting Skip — AI-Powered Bookkeeping',
    description: 'Month-end close in 5 days. AI + QBO-certified accountants. Starting at $349/month.',
    images: ['/opengraph-image'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
        {/* Favicon generated by app/icon.tsx */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'AccountingService',
              name: 'Accounting Skip LLC',
              description: 'AI-powered bookkeeping for US small businesses',
              url: 'https://accountingskip.com',
              telephone: '+1-305-555-0123',
              email: 'team@accountingskip.com',
              address: {
                '@type': 'PostalAddress',
                addressRegion: 'FL',
                addressCountry: 'US',
              },
              priceRange: '$$',
              areaServed: 'US',
            }),
          }}
        />
      </head>
      <body className="antialiased bg-navy text-white">
        <a href="#main-content" className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[9999] focus:btn-primary">
          Skip to main content
        </a>
        <Navbar />
        <main id="main-content">{children}</main>
        <Footer />
        <CookieBanner />
      </body>
    </html>
  )
}
